version: 0.2

env:
  variables:
    M2_HoME: /usr/local/apache-maven/apache-maven-3.3.9
    M2: $M2_HOME/bin
    PATH: $M2\:$PATH
    
    
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install maven3
      - mvn -v
    
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - ls
artifacts:
  files:
    - target/spring-boot-web-jsp-1.0.war
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
