version: 0.2
env:
  variables:
     - M3_HOME: /usr/bin/mvn

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
  
    
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - unset M2_HOME
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - ls
artifacts:
  files:
    - target/*.war
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
