version: 0.2


    
    
phases:
  install:
    commands:
      - apt-get update -y 
      - apt-get install maven
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo 'build successful'
artifacts:
  files:
    - target/spring-boot-web-jsp-1.0.war
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
